application:
  title: User Service
  version: 1.0

server:
  port: 5001
#  data:
#    mongodb:
#      authentication-database: admin
#      username: rootuser
#      password: rootpass
#      database: user
#      port: 27017
#      host: localhost

#      spring.data.mongodb.authentication-dsatabase=admin
#      spring.data.mongodb.username=rootuser
#      spring.data.mongodb.password=rootpass
#      spring.data.mongodb.database=user
#      spring.data.mongodb.port=27017
#      spring.data.mongodb.host=localhost
#      server.port=5001

spring:
  jpa:
    properties:
      hibernate:
        format_sql=true:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
