application:
  title: Message Service
  version: 1.0

server:
  port: 5002

spring:
  jpa:
    properties:
      hibernate:
        format_sql=true:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/3b94b4c6-59a7-4d4f-b594-532eadaff784/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/3b94b4c6-59a7-4d4f-b594-532eadaff784/v2.0
          audiences: 82b5a9e1-eaa2-4ee8-a3a0-7d3c41a4a1b5
  data:
    mongodb:
      uri: mongodb+srv://root:3okKI5iGkWoznG7W@cluster0.tcj1n9o.mongodb.net/?retryWrites=true&w=majority
      database: messages
      auto-index-creation: true